### ISSUE TITLE
Adapter free front attachment does not seem consistent

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFutureConstruction#1]
Some of your adapters can attach other things (without an attachment node) on the front, and others can't. I'm not sure it's intentional.

Here's the ones that can attach:

![attachment-front](https://cloud.githubusercontent.com/assets/592826/12005958/6f8999a2-abbf-11e5-9f56-98fb24e5293a.jpeg)

And these are the ones that can't:

![no-attachment-front](https://cloud.githubusercontent.com/assets/592826/12005969/d7b264d2-abbf-11e5-8c49-15fe890b0404.jpeg)

**Comment by ChrisAdderley** [comment]
That's weird indeed. I'll investigate this, I don't know how I could have accomplished it.

**Comment by ChrisAdderley** [comment]
These models were all deprecated, so i'm closing this.
