### ISSUE TITLE
Version 0.6.2 is missing a bundled dependency

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureConstruction#10]
GameData\NearFutureConstruction\Patches\NFConstructionFuelTankTypes.cfg tries to set up tank configs for CRP resources. However, CRP is not included in the download.

In a scenario where all Near Future packs are installed together, this has no effect, as CRP is bundled with other downloads. But NF Construction alone will hang on startup.

**Comment by ChrisAdderley** [comment]
Resolved by fixing the missing :NEEDS on that fuel tank type. Will be in 0.6.3
