### ISSUE TITLE
truss-octo-angled-crew-01 cfg error

### ISSUE THREAD

**Issue by adam-andrus-ama** [ChrisAdderley/NearFutureConstruction#116]
from ksp log

[LOG 12:54:46.960] PartLoader: Compiling Part 'NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-angled-crew-01/truss-octo-angled-crew-01'
[WRN 12:54:46.963] PartLoader Warning: Variable ode_attach not found in Part

it appears that there is an error in the cfg file:
unclear what issues this is causing, I just noticed this when researching my log file for other issues.

node_stack_top01 = 0.0, 1.199, 1.244, 0.0, 0.0, 1.0, 2
	node_stack_top02 = 0.0, 0.899, 0.4018, 0.0, 0.5, 0.5, 2
	node_stack_top03 = 0.0, 0.665, 0.197, 0.0, 0.86602540378, 0.5, 2
	node_stack_bottom = 0.0, -0.07155213, 0.0, 0.0, -1.0, 0.0, 2
	**ode_attach** = 0.0, -0.07155213, 0.0, 0.0, -1.0, 0.0, 2

**Comment by ChrisAdderley** [comment]
Resolved for next version
