### ISSUE TITLE
Tank type patches don't target the fuelSwitch B9PS module correctly

### ISSUE THREAD

**Issue by JonnyOThan** [ChrisAdderley/NearFutureConstruction#122]
https://github.com/post-kerbin-mining-corporation/NearFutureConstruction/blob/f6cfd425eb4ea5673bb00ba1b39b21719418524a/GameData/NearFutureConstruction/Patches/NFConstructionCRPTrusses.cfg#L8

These patches target the first ModuleB9PartSwitch in the part, which sometimes happens to be the meshSwitch one.  These need `:HAS[#moduleID[tankSwitch]]` added to them.

**Comment by ChrisAdderley** [comment]
Resolved
