### ISSUE TITLE
Pressurized Modular Annular Truss

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/NearFutureConstruction#24]
Same as Modular Annular Truss but with CLS and pressurized centre core.
- [ ] Model
- [ ] Unwrap
- [ ] Texture
- [ ] cfg

**Comment by Vladimir-csp** [comment]
With these large structures it would be interesting to put pressurized tubes on the sides and leave the center for cargo hauling.

**Comment by ChrisAdderley** [comment]
Descoped.
