### ISSUE TITLE
Exception on startup related to truss-circular-docking-01

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureConstruction#29]
Issue does not prevent the game from loading, but it may prevent the part from having a proper drag cube.

Confirmed on a fresh install running only Module manager and NF Construction.

http://forum.kerbalspaceprogram.com/index.php?/topic/47786-12-near-future-technologies-oct-21-12-updates-for-all/&do=findComment&comment=2818684

**Comment by ChrisAdderley** [comment]
Related to an animation export for the docking lights that went wrong.

**Comment by ChrisAdderley** [comment]
Resolved for 0.7.1
