### ISSUE TITLE
S-MED uses wrong scaling

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureConstruction#3]
S-MED adapter scales model instead of whole part. Sinks into surface when attached.

**Comment by ChrisAdderley** [comment]
It's actually that the attach node hasn't been repositioned, but same effect.

**Comment by Vladimir-csp** [comment]
Not only. Stack nodes sink into adapter too. Skinny girl in a fat body )

**Comment by ChrisAdderley** [comment]
Nodes, attach nodes... whole dealie :).

**Comment by Vladimir-csp** [comment]
Just remove:

```
       scale = 2.0,2.0,2.0
...
scale = 1
```

And change:

```
rescaleFactor = 2.0
```

Should do the thing. I'll test it soon.

**Comment by ChrisAdderley** [comment]
This is a deprecated method of scaling though, and we've been informed that it's unreliable and that rescaleFactor of 1.0 should always be used.

**Comment by ChrisAdderley** [comment]
Fixed with new models.
