### ISSUE TITLE
Modular Annular Truss Adapter model change?

### ISSUE THREAD

**Issue by alexey-koktysh** [ChrisAdderley/NearFutureConstruction#30]
Part named "truss-circular-adapter-01" has a permanent non-adjustable "Core truss" part which can be adjusted for other trusses, but not this adapter.
Would be nice to have it adjustable. Not crucial though.

**Comment by ChrisAdderley** [comment]
Will be a bit of a pain to implement, but probably worth it. Will also adjust the colliders to make this part hollow for internal attachment.

**Comment by ChrisAdderley** [comment]
Resolved and will be shipped in next version.

**Comment by alexey-koktysh** [comment]
Thanks :) Really appreciate this.
