### ISSUE TITLE
Frame trusses

### ISSUE THREAD

**Issue by AmpCat** [ChrisAdderley/NearFutureConstruction#39]
Would like a structural frame to go around parts that lack radial attachment points, like long KA engines, so things like landing gear, tanks, and fins can be attached near the exhaust/bell, while the engine sits inside the frame. 2.5m is especially useful, 3.75 and possibly 1.25 would be as well. This would also work for enclosing reactors or other components that you may want exposed on one end.

**Comment by sdfg2** [comment]
I love this idea.  I mean, I love the various tank setups that there are already, they look really good, but not all resources are there, and yeah, sometimes you want to shove other bits and bobs in there too.  Imagine how good it would look with some Kontainers inside!

EDIT:  It's there already.  Set the truss type to 'open' and it looks just like any other cargo bay.  You can then set it back to 'closed' if you want.  :-D

**Comment by ChrisAdderley** [comment]
I think he means like am open truss chopped in two. Little different.
