### ISSUE TITLE
2.5m and 3.75m Orbital Engines creating torque

### ISSUE THREAD

**Issue by TykoTek** [ChrisAdderley/NearFutureConstruction#47]
As measured in KER in VAB, the 2.5m and 3.75m Orbital Engines are causing torque on the spacecraft

Step to reproduce:
- In VAB (KSP 1.2.2)
- With KER installed. Current version 1.1.2.8
- Select a Mk3-9 command pad
- snap a 2.5m or 3.75m orbital engine onto the command pod

Outcome 
- 2.5m setup shows 0.14kNm torque
- 3.75m setup shows 1.94kNm torque

**Comment by ChrisAdderley** [comment]
Did you mean to post this in NF spacecraft? ;)

It's fixed anyways (https://github.com/ChrisAdderley/NearFutureSpacecraft/commit/92d261f4da032fe8406d8c98b02995deec1761b6)

**Comment by TykoTek** [comment]
Yea..sorry about the misfiling. Thanks!
