### ISSUE TITLE
Modular Spinal Truss Docking Connector does not snap to 90 degree angles.

### ISSUE THREAD

**Issue by gabevenberg** [ChrisAdderley/NearFutureConstruction#48]
it seems to snap to a 360 degree angle, there is only one orientation it connects in.

**Comment by gabevenberg** [comment]
the Modular Octagonal Docking Connector also has a similar problem. it will snap to 45 degree angles, instead of 90. it seems you just made a typo in the .cfgs. also, maybe add acquireTorque to them? i can make a PR fixing this if you want.

**Comment by ChrisAdderley** [comment]
I didn't notice this issue before, I will look into it. However, I tested each of these parts as they were added, and they didn't exhibit any of these problem. Mind you it's possible that something changed in KSP to invalidate that testing. 

Even so, can I have a mod list?

**Comment by gabevenberg** [comment]
about 150 mods, not all of them are tracked by avc, but to confirm, i looked at the .cfgs, and the spinal truss has SnapOffset at 0, and the hex one has it at 45. changing both of these values to 90 fixed the problem.
if you want, i can give you the avc output, but looking at the documentation for stock [here](http://wiki.kerbalspaceprogram.com/wiki/Module#ModuleDockingNode), it seems that the value should be 90.

**Comment by ChrisAdderley** [comment]
Resolved in upcoming 0.7.6
