### ISSUE TITLE
Modular Octagonal Docking Connectors From Previous Versions Cannot Undock

### ISSUE THREAD

**Issue by Sarai91** [ChrisAdderley/NearFutureConstruction#5]
KSP 1.1.2
NFC 0.6.1

When attempting to separate two Modular Octagonal Docking Connectors, clicking the Undock button causes the button to disappear without the vessels separating, and the status remains as Locked. Both Connectors were created in a previous version of NFC, and were docked when updated to 0.6.1. The Undock button will not reappear even if KSP is exited and restarted, a prior save must be loaded; however this will still not allow Undocking. 

Docking and Undocking with another Modular Octagonal Docking Connector created in 0.6.1 functions as normal, even if one of the two is from a previous version (the one without an Undock button). I am unable to test if this issue applies to other docking connectors as I have no other connectors present from prior versions.

**Comment by ChrisAdderley** [comment]
What is defined as a previous version? 0.6.0?

**Comment by Sarai91** [comment]
I believe so. I don't recall exactly, but it was the most recent version up until the 0.6.1 update for 1.1.2. If that was 0.6.0 for 1.1 then yes.

**Comment by StarStreak2109** [comment]
Hi there,
I have exactly the same issue as Sarai91. Trying to undock two octotruss docking connectors. After clicking the "Undock" button, said button disappears, and status remains as "Locked".

If that helps I have attached the persistant file. Running on NFC 0.6.4.

[persistent.zip](https://github.com/ChrisAdderley/NearFutureConstruction/files/384747/persistent.zip)

**Comment by ChrisAdderley** [comment]
Logs and mod list?

**Comment by StarStreak2109** [comment]
Hi, here is the log file and my mod list. 
[modlist.txt](https://github.com/ChrisAdderley/NearFutureConstruction/files/385548/modlist.txt)
[KSP.log.zip](https://github.com/ChrisAdderley/NearFutureConstruction/files/385549/KSP.log.zip)

To further extend on the issue: I restarted KSP and checked all Octogirder Docking Connectors. All of them are locked w/o the possibility to undock. "Normal" clampotron docking ports work normally, even those connected to one of the octos...

**Comment by ChrisAdderley** [comment]
Yeah... see I still can't repro this. It has to be some kind of mod conflict - can you at all provide a simple list of repro steps that result in the issue? So far I have tried
1. Create ship made of 2 docking test ships (1x large RCS tank, 4x quad RCS block, 1x 2.5m drone core, 1x 2.5 m battery, 1x  docking connector) stuck together
2. Launch ship
3. Undock, redock, repeat several times
4. Return to tracking station, return to ship, repeat dock/redock several times

Tried by hyperediting into orbit and going through a whole regular launch. No issues docking or undocking were seen at all

**Comment by Sarai91** [comment]
I don't have my mod list or log as I'm not at home, but this issue only affects ships that were docked using version 0.6.0, then undocking was attempted running version 0.6.1. Ships docked under 0.6.1 or later can undock normally.

**Comment by smurphy34** [comment]
I beleve this is a [stock bug](http://forum.kerbalspaceprogram.com/index.php?/topic/142382-clamp-o-tron-not-working-v113/&page=2#comment-2660696),

**Comment by ChrisAdderley** [comment]
Ah I see... well, closing again!
