### ISSUE TITLE
0.625 > 1.25 Adapter

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/NearFutureConstruction#52]
New Part Request: Additional 0.625m >1.25m adapter to complete the set. Either a small Rockomax Skeletal Structural Adapter or SM-1 Single Stack Adapter. I didn't know I wanted it, until I couldn't have it.

To be used as a thrust plate for 1.25m stacks to 0.625m engines where 2 engines are too much, but one is just right. Or as an adapter for non engine applications. Probably other stuff too.

Cheers,

**Comment by ChrisAdderley** [comment]
Added to next major version scope.
