### ISSUE TITLE
Octo-Girder Pressurized Angular Connector (30 Degree) - not actually 30 degrees!

### ISSUE THREAD

**Issue by sdfg2** [ChrisAdderley/NearFutureConstruction#59]
![screenshot_20170731_234727](https://user-images.githubusercontent.com/5736478/28801655-717b600e-764a-11e7-9533-940d56394de7.png)

The picture says it all I think. :-)

**Comment by nirbhayjm** [comment]
I have experienced this too, can't use them for circular connections like the hexagon in your image.

**Comment by ChrisAdderley** [comment]
I'll investigate this, but what would reaaaaaly help would be if someone would give me the right coordinate this time

**Comment by sdfg2** [comment]
I'd be happy to help if I knew what you meant.  Knowing nothing about it whatsoever, there might be a clue in the non-pressurized struts given they work flawlessly?
