### ISSUE TITLE
6 and 8 point hubs

### ISSUE THREAD

**Issue by sdfg2** [ChrisAdderley/NearFutureConstruction#60]
Love your work, seriously.  Absolutely beautiful.

One thing I'd love would be 6 and 8 point hubs, to go with the 30 and 45 degree angular trusses you have.  Everyone loves rings!

I do understand that with the pressurized trusses it may be more problematic, depending on your solution of course.  Looking at something like the 6 way connector from Chopshop, it also adapts the size from 2.5m to 1.25m - if you went for a similar solution to that I guess we'd need adaptors to make sure the diameter of the pressurized tube remains the same?  So the tube diameter remains the same and the truss diameter increases (a bit like 5m to 3.75m, or 5m to 2.5m adaptors from USI.  I mean they work fine with your trusses, but the visual inconsistency bugs my OCD ;-) ).

**Comment by ChrisAdderley** [comment]
Aren't there six point hubs already? and what does an 8 point hub look like?

**Comment by sdfg2** [comment]
Ah yes sorry, I should have said 8 and 10 point hubs.  I was confused because ChopShop refers to the 8 way hub as a '6 way connector'.  It's like a 6 point hub, except it has 6 radial nodes instead of 4.

Here's the one from ChopShop (TweakScaled - Top is 5m, each side part is 2.5m).

![screenshot_20170801_212541](https://user-images.githubusercontent.com/5736478/28845402-cd909a3e-76ff-11e7-9816-1d4456b7603e.png)

**Comment by ChrisAdderley** [comment]
Unfortunately, decided against this.
