### ISSUE TITLE
Grip-O-Tron Large Docking Connector Doesn't Show Up in Game

### ISSUE THREAD

**Issue by asher-m** [ChrisAdderley/NearFutureConstruction#61]
Grip-O-Tron Large Docking Connector doesn't show up in game.

I was able to fix the issue in my local repo by changing:
`category = none`
in NearFutureConstruction/GameData/NearFutureConstruction/Parts/Structures/docking-25/docking-25.cfg to:
`category = Coupling`

**Comment by ChrisAdderley** [comment]
Not a bug, part is deprecated. Left ingame to not break ships.
