### ISSUE TITLE
Kontainer-proportioned struts

### ISSUE THREAD

**Issue by sdfg2** [ChrisAdderley/NearFutureConstruction#62]
Would it be possible to get a strut that is the same proportion as a Kontainer?  At the moment the existing ones are just a little too short :-(  Which is a shame because the two go together beautifully.

![screenshot_20170801_213313](https://user-images.githubusercontent.com/5736478/28845710-d2599f88-7700-11e7-80a5-085c7fdcdedb.png)

**Comment by ChrisAdderley** [comment]
Decided against this
