### ISSUE TITLE
Texture 'NearFutureConstruction/Parts/Truss/truss-octo/octo-truss-xe-util-01-n' not found

### ISSUE THREAD

**Issue by MaximeBrean** [ChrisAdderley/NearFutureConstruction#75]
As the title say, the `NearFutureConstruction/Parts/Truss/truss-octo/octo-truss-xe-util-01-n` texture is not found for version 1.0.0. This error raised for the two following parts:
- `NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-01`
- `NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-02`

**Comment by ChrisAdderley** [comment]
Fixed for next version
