### ISSUE TITLE
Micronode nodes

### ISSUE THREAD

**Issue by alexey-koktysh** [ChrisAdderley/NearFutureConstruction#78]
NF Construction v. 1.0.1 has a stock overriding part - NearFutureConstruction/Parts/Truss/truss-micro/truss-micro-3 - which has somewhat shifted attachment nodes.

**Comment by ChrisAdderley** [comment]
So I didn't touch the nodes. I'm assuming this is the mesh moving. Can you provide me with some pictures, perhaps?

**Comment by alexey-koktysh** [comment]
Here's the picture.
![nodes_problem](https://user-images.githubusercontent.com/4668647/38752876-51ae5e68-3f65-11e8-91ed-3231efbd711d.jpg)

**Comment by ChrisAdderley** [comment]
Thanks, I'll see what's going on.

**Comment by ChrisAdderley** [comment]
Should be resolved in latest release.
