### ISSUE TITLE
en-us bugs

### ISSUE THREAD

**Issue by doktorjet** [ChrisAdderley/NearFutureConstruction#79]
1) _#LOC_NFConstruction_switcher_profile_planar = Triangular_

From other localization strings, I believe it should be:

_#LOC_NFConstruction_switcher_profile_planar = Planar_

2) _#LOC_NFConstruction_adapter-375-25-2_description =_
String missing.

**Comment by ChrisAdderley** [comment]
The second one isn't actually a part, but the first one has been resolved for the next version

**Comment by ChrisAdderley** [comment]
Should be resolved in latest release.
