### ISSUE TITLE
Octo-Girder Pressurized Truss XL lights incorrectly placed

### ISSUE THREAD

**Issue by Svish** [ChrisAdderley/NearFutureConstruction#81]
This doesn't look right. 🤔

![screenshot](https://user-images.githubusercontent.com/142162/38771536-2face0d0-4025-11e8-91c1-de81325fb207.jpg)

**Comment by Svish** [comment]
Seems to be the case with all the Octo-Girder Pressurized Truss variants... 😕

**Comment by ChrisAdderley** [comment]
The old texture was shipped by accident. It'll be fixed whenever I have time to release the next version.

**Comment by ChrisAdderley** [comment]
Should be resolved in latest release.
