### ISSUE TITLE
Docking Port - "Top" and VAB Orientation

### ISSUE THREAD

**Issue by quade-ksp** [ChrisAdderley/NearFutureConstruction#87]
First -- FANTASTIC MOD. Seriously well done.

Okay, now to the issue.

I'm using the stock Sr. sized docking port here as reference since it's by far the easiest to see the orientation of and using the VAB since that too is the easiest.

In stock pick and place, the stock Sr. sized port has the gold "handle" pointing toward north in the VAB (and how it will show up on the launch pad as well if not rotated).  If you look at the (non-functioning) EVA handles they form a "Y" with the bottom of the "Y" facing north as well.

The Octo-Girder Heavy Docking Connector, EVA handles seem rotated about 170° clockwise as viewed top down by comparison.

I know this is a minor graphics issue, but without easy identification of the "north" part of components, it's all too easy to construct something that ends up as a suprise when docked in orbit.

<img width="811" alt="screen shot 2018-09-08 at 8 51 19 pm" src="https://user-images.githubusercontent.com/35043614/45260939-33850280-b3a9-11e8-9ef9-93307df9b616.png">

Thank you for your time and efforts.  Again, fantastic mods.

**Comment by ChrisAdderley** [comment]
I appreciate the very detailed bug reports - thanks!
This is super minor for me unfortunately - I'll try to ensure it makes it into a future release, but not sure when that will be.

**Comment by quade-ksp** [comment]
Thank you, sir.

**Comment by ChrisAdderley** [comment]
Ready in next version
