### ISSUE TITLE
Linear docking ports unavailable in career mode

### ISSUE THREAD

**Issue by Wyzard256** [ChrisAdderley/NearFutureConstruction#88]
The two linear docking ports (Grip-O-Tron Linear and Grip-O-Tron XL Linear) are inaccessible in career mode because they have `TechRequired = Unresearchable` in their config files, so they don't appear in the tech tree.  (They're available in sandbox mode, since that has all parts unlocked regardless of whether they're actually in a tech node.)

**Comment by ChrisAdderley** [comment]
This has been resolved in dev for a bit now, I hope to release it soon.

**Comment by Wyzard256** [comment]
This has been resolved by the release of version 1.0.4.
