### ISSUE TITLE
Octagonal Docking Connector: Misaligned Docking Nodes/Physics Colliders 

### ISSUE THREAD

**Issue by TylerFBenson** [ChrisAdderley/NearFutureConstruction#99]
The Octo-girder Octagonal Docking Connector has difficulty properly docking, due to the fact that the docking nodes and physics collider are too far apart. This post on the KSP forums covers the issue in more detail.

https://forum.kerbalspaceprogram.com/index.php?/topic/155465-17x-near-future-technologies-enormous-nf-solar-update-may-12/&do=findComment&comment=3620150

**Comment by ChrisAdderley** [comment]
Fixed in dev and ready for next version.

**Comment by ChrisAdderley** [comment]
Released.
